### ISSUE TITLE
Calling ClearQuery has no effect 

### ISSUE THREAD

**Issue by OmarAljoundi** [iamhectorsosa/search-params#9]
First off, I want to say I'm impressed with your library – great job on that.
I've run into a bit of a snag, though. I'm having trouble getting the **ClearQuery()** method to work properly. I think I might have missed a step in the setup or something. Any ideas on what I could be overlooking?

Here is my configuration, I'm using Zod for validation. 
`  import { createSearchParamsConfig } from "@search-params/react";
import { z } from "zod";

const searchParamsSchema = z.object({
  searchInterval: z
    .object({
      timeTense: z.string().optional(),
      label: z.string().optional(),
      timeValue: z.number().min(1).optional(),
      timeUnit: z.string().optional(),
    })
    .optional()
    .default({}),

  index: z.string().optional(),
  query: z.string().optional(),
});

export const config = createSearchParamsConfig({
  home: (search) => searchParamsSchema.parse(search),
}); `

My clear button 
`use client";

import { FunctionComponent } from "react";
import { Button } from "../../ui/button";
import { useSearchParams } from "@search-params/react";
import { config } from "@/app/_lib/search-config";

interface ClearQueryProps {}

const ClearQuery: FunctionComponent<ClearQueryProps> = () => {
  const { clearQuery } = useSearchParams({
    route: config.home,
  });
  return (
    <Button onClick={() => clearQuery()} variant={"destructive"}>
      Clear Search
    </Button>
  );
};

export default ClearQuery;`

- react: ^18
- zod: ^3.22.4
- next: 14.0.4
- node: v20.9.0

Thank you!

**Comment by iamhectorsosa** [comment]
Hello, @OmarAljoundi ! Thanks for submitting this issue. When using Zod I would recommend checking out the method: Catch https://zod.dev/?id=catch This method will allow you to provide a fallback or default value. What the `clearQuery` method does is that it sets the value to whatever the default is.

Please let me know if this resolves your issue. Feel free to share a link to the repo I can take a look and if we need to do any changes to the `clearQuery` method I'm open to suggestions. Here is the source of this method: https://github.com/iamhectorsosa/search-params/blob/af4f62319ae9f06588cfc287f83fb2cf1eae7b2a/packages/react/src/hooks/index.ts#L59-L67 it calls your validator function without any arguments. Which allows your validator function to set its defaults.

**Comment by OmarAljoundi** [comment]
Thank you for your quick response @iamhectorsosa!
I tried adding "Empty string",  "undefined" and "null" as a default value, but still calling the clear query has no effect 

```
 import { createSearchParamsConfig } from "@search-params/react";
import { z } from "zod";

export const searchParamsSchema = z.object({
  searchInterval: z
    .object({
      timeTense: z.string().optional(),
      label: z.string().optional(),
      timeValue: z.number().min(1).optional(),
      timeUnit: z.string().optional(),
    })
    .optional()
    .nullable()
    .default(null),

  index: z.string().optional().nullable().default("all"),
  query: z.record(z.any()).optional(),
});

export const config = createSearchParamsConfig({
  home: (search) => searchParamsSchema.parse(search),
});

```

I logged the parsing result
```
{
    "searchInterval": null,
    "index": "all" // if the default was a valid string it falls to it, otherwise nothing changes
}
```

I'm trying to achieve what you have provided in the playground 
**_https://search-params-playground.vercel.app/?page=1&item=Shirt_** 
when clearing the query, the "**item**" query gets fully deleted. 

if you still need a demonstration, let me know.
Thank you!

**Comment by iamhectorsosa** [comment]
This might be a limitation that we might have to address from the library-side.

Reading Zod's documentation. It seems that it doesn't allow a catch value to be undefined or null (did you try the method catch?).

So this "clearing the value" wouldn't be possible using Zod. My example uses Valibot which does allow a fallback value to be undefined, therefore removing the parameter.

I chose to rely on the validation function because you default the defaults there. Clear params should give you the defaults not just clear the params. I didn't consider that some schema validation libraries might not be able to provide an undefined or null value for these.

**Comment by OmarAljoundi** [comment]
I was able to clear the query eventually by passing the same example above  (didn't know why it wasn't working before) 
Passing the default value as null solved my problem, referring to this:
https://github.com/iamhectorsosa/search-params/blob/af4f62319ae9f06588cfc287f83fb2cf1eae7b2a/packages/react/src/utils/index.ts#L25C1-L48C2

Thank you @iamhectorsosa !

**Comment by iamhectorsosa** [comment]
Happy to hear that you found a solution.

I'd be thrilled to see your implementation. If possible and whenever you'd like to, do share your project! Thank you! ❤️
